// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALgsbbLmOpxqJX7K4sQsCVtPbHGfrsj9o',
    appId: '1:390340839802:web:5ecfaeac5c4e265b986ec3',
    messagingSenderId: '390340839802',
    projectId: 'schedule-management-98cdf',
    authDomain: 'schedule-management-98cdf.firebaseapp.com',
    storageBucket: 'schedule-management-98cdf.firebasestorage.app',
    measurementId: 'G-M6014BWJ2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbRSZwL5rMHQSHWMcSzM__oA6iz5qlFPQ',
    appId: '1:390340839802:android:66fd35edb9f1f868986ec3',
    messagingSenderId: '390340839802',
    projectId: 'schedule-management-98cdf',
    storageBucket: 'schedule-management-98cdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0x3tadDghBy2IqP1BhcE2Q4J_lCS9dno',
    appId: '1:390340839802:ios:2b791350e290533a986ec3',
    messagingSenderId: '390340839802',
    projectId: 'schedule-management-98cdf',
    storageBucket: 'schedule-management-98cdf.firebasestorage.app',
    iosBundleId: 'com.schedulo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0x3tadDghBy2IqP1BhcE2Q4J_lCS9dno',
    appId: '1:390340839802:ios:2b791350e290533a986ec3',
    messagingSenderId: '390340839802',
    projectId: 'schedule-management-98cdf',
    storageBucket: 'schedule-management-98cdf.firebasestorage.app',
    iosBundleId: 'com.schedulo.app.macos',
  );
}
